name: Jenkins Pipeline

on:
  [push, pull_request]

jobs:
  Jenkins-PR:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Variables
        run: |
          echo "$CI_HEAD_REF"
      - name: Print
        run: echo ${{ env.CI_ACTION_REF_NAME }}
      - name: Trigger-unit-test
        uses: mledot/jenkins-trigger@main        
        with:
          url:  "http://3.21.156.14"
          user_name: "morgan" # user name for accessing jenkins
          api_token: "11e9875440abdb6b0d715549a977acc47e" # personal Access token for accessing Jenkins
          job_name: "SamplePR" # The name of the jenkins job to run
          parameter: { "branch": "${{ env.CI_ACTION_REF_NAME }}" }
          timeout: "5000"