name: Jenkins Pipeline

on:
  [push, pull_request]

jobs:
  Jenkins-PR-create:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Variables
        run: |
          echo "$CI_HEAD_REF"
      - name: Trigger-unit-test
        uses: mledot/jenkins-trigger@main      
        with:
          url:  "${{ secrets.JENKINS_URL }}"
          user_name: "${{ secrets.JENKINS_USER }}" # user name for accessing jenkins
          api_token: "${{ secrets.JENKINS_PASS }}" # personal Access token for accessing Jenkins
          job_name: "SamplePR" # The name of the jenkins job to run
          # parameter: '{"branch": "${{ env.CI_ACTION_REF_NAME }}", "repo":"${{ env.CI_REPOSITORY_NAME }}", "base":"${{ env.CI_BASE_REF }}"}'
          timeout: "5000"